# Generated by Django 4.2 on 2023-04-07 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 11, 15, 49, 250531, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
