# Generated by Django 4.2 on 2023-04-07 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 11, 24, 0, 78138, tzinfo=datetime.timezone.utc)),
        ),
    ]
