# Generated by Django 4.2 on 2023-04-07 11:38

import datetime
from django.db import migrations, models
import pins_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('pins_api', '0002_pin_content_alter_pin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.ImageField(default='pins/default.jpg', upload_to=pins_api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 11, 38, 58, 315184, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
