# Generated by Django 4.2 on 2023-04-07 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins_api', '0003_pin_image_alter_pin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='pin',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='pin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 11, 45, 4, 535669, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
